name: sample mvn application

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch from github
        uses: actions/checkout@v2

      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build mvn project
        run: mvn -B package --file pom.xml

      - name: list current dir
        run: ls -la

      - name: ls target dir
        run: |
          pwd
          cd target
          ls -a

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: example-jar
          path: .sample/
